version: '3.0'

services:
  db: 
    image: mcr.microsoft.com/mssql/server
    container_name: db-container
    environment:
      SA_PASSWORD: "tUr1sm0S4lLD4&"
      ACCEPT_EULA: "Y"
    ports:
    
      - "1433:1433"
    volumes:
      - DB:/var/opt/mssql
    
volumes:
  DB:
# 192.168.72.223
